### ISSUE TITLE
ctime (and possibly asctime) pulls in 2.0+ strftime with -mcrt=nix13

### ISSUE THREAD

**Issue by rvalles** [bebbo/libnix#57]
Using bebbo/amiga-gcc release "Mehchen".

test.c is just:
```
#include <time.h>
int main() {
    ctime((time_t*) 0);
}
```

When attempting to build it with -mcrt=nix13, it fails on linking:

```
$ /opt/amiga/bin/m68k-amigaos-gcc -mcrt=clib2 test.c #fine
$ /opt/amiga/bin/m68k-amigaos-gcc -mcrt=nix20 test.c #all good
$ /opt/amiga/bin/m68k-amigaos-gcc -mcrt=nix13 test.c
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/m68k-amigaos/libnix/lib/libnix.a(strftime.o): in function `strftime':
strftime.o:(.text+0x302): undefined reference to `__localevec'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: strftime.o:(.text+0x34c): undefined reference to `__localevec'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: strftime.o:(.text+0x3b2): undefined reference to `__localevec'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: strftime.o:(.text+0x492): undefined reference to `__localevec'
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: strftime.o:(.text+0x4b4): undefined reference to `__localevec'
collect2: error: ld returned 1 exit status
```

Whereas a similar test, but calling strftime instead, does not exhibit this issue.

Therefore, somehow, ctime (and likely asctime too) are pulling 2.0 version of strftime, despite crt13.

**Comment by rvalles** [comment]
Test program does now build and run on 3.1 with nix13.

It does, however, not work on 1.3 (demands utility.library, which doesn't exist for 1.3).

OTOH the program I was trying to build (gzip 1.2.4a), does now build and then runs on 3.2 with nix13, but that binary outright crashes on 1.3 (despite 32KB stack) with a 0..B guru (F line emulation).

All tests on A1200, with blizzard 1230mkIV (030+882@50 & 128M RAM), using blizkick for kick34.

**Comment by bebbo** [comment]
gzip 1.2.4a does build and run now - with the recent changes

**Comment by rvalles** [comment]
It does build with nix13 and runs properly on 3.x.

On 1.3, however:

![image](https://user-images.githubusercontent.com/422753/200241367-ab24999a-378b-4882-a216-b60a1c14f880.png)

It's close, but something's still off.

**Comment by bebbo** [comment]
My version is able to unzip:
[gzip.gz](https://github.com/bebbo/libnix/files/9950271/gzip.gz)

**Comment by rvalles** [comment]
I have now tested your binary:
  
![image](https://user-images.githubusercontent.com/422753/200284603-a7cd36fd-b9c3-4d4a-80c4-ba229132c18e.png)

I have no idea either.

**Comment by bebbo** [comment]
it's the drive/volume `RAM:`

**Comment by rvalles** [comment]
![image](https://user-images.githubusercontent.com/422753/200294800-bdf1859b-324f-4782-bb90-99627223d3ad.png)

No dice.

**Comment by bebbo** [comment]
[gzip.gz](https://github.com/bebbo/libnix/files/9951419/gzip.gz)

please test

**Comment by rvalles** [comment]
Now it runs, somewhat. It can compress and decompress a small file (used s:startup-sequence).

But it seems to have trouble with a larger one:

![image](https://user-images.githubusercontent.com/422753/200319894-5a7406a7-91ea-4053-95a0-c976563bfd3d.png)


```
[rvalles@yukino pyamigadebug]$ gunzip asmtwo.gz

gzip: asmtwo.gz: invalid compressed data--crc error

gzip: asmtwo.gz: invalid compressed data--length error
[rvalles@yukino pyamigadebug]$ file asmtwo.gz
asmtwo.gz: gzip compressed data, was "asmtwo", last modified: Tue Nov  7 13:12:04 2000, from Amiga, original size modulo 2^32 97312
```

**Comment by bebbo** [comment]
sorry - that is beyond the scope here. But I noticed that there is a fixed version on Aminet which mentions some bug in `match.S`.

**Comment by rvalles** [comment]
> sorry - that is beyond the scope here. But I noticed that there is a fixed version on Aminet which mentions some bug in `match.S`.

I'll rebuild the toolchain now; I do build my gzip w/o match.S (because I can't be bothered to use the .a in the tarball... and I guess it's bad after all), then the c version is used.

I'll let you know how that goes.

**Comment by rvalles** [comment]
Yep. The one I built (not using match.S at all) is good.

I can now crunch and decrunch that same file w/o issue.
